apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
    spec:
      containers:
        - name: primary
          env:
            - name: env
              value: dev
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
---
