FROM golang:1.20-alpine AS builder

RUN apk update && apk add --no-cache git && apk --no-cache add ca-certificates

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy
RUN go mod download

COPY . .

ARG FIREBASE_CREDENTIALS
RUN echo ${FIREBASE_CREDENTIALS} | base64 -d > configs/buffer-box-firebase-credentials.json

RUN go build -trimpath -ldflags "-s -w -extldflags '-static'" -o main app/main.go

FROM golang:1.20-alpine 
RUN adduser -D -u 1000 carbonform-backend
COPY --from=builder /app/main .
COPY --from=builder /app/configs/dev.yml ./configs/dev.yml
COPY --from=builder /app/configs/buffer-box-firebase-credentials.json ./configs/buffer-box-firebase-credentials.json
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/template/ ./template/


RUN apk update && apk add --no-cache curl

ENV TZ=Asia/Bangkok
USER carbonform-backend
ENTRYPOINT ["./main", "dev"]
