apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
spec:
  selector:
    matchLabels:
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
    spec:
      containers:
        - name: primary
          env:
            - name: env
              value: prod
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
            
---
