apiVersion: v1
kind: Secret
metadata:
  name: ${app_name}-secret
data:
  MSSQL_DATABASE: $MSSQL_DATABASE_PROD
  MSSQL_USER: $MSSQL_USER_PROD
  MSSQL_PASSWORD: $MSSQL_PASSWORD_PROD
  MSSQL_HOST: $MSSQL_HOST_PROD
  MSSQL_PORT: "$MSSQL_PORT_PROD"
  EMAIL_USERNAME: $EMAIL_USERNAME_PROD
  EMAIL_PASSWORD: $EMAIL_PASSWORD_PROD
  TOKEN_SCS_CHECKCARBONREGISTER: $TOKEN_SCS_CHECKCARBONREGISTER_PROD